Image: "jenkinsxio/exposecontroller"
ImageTag: "2.3.58"
BackoffLimit: 5
Annotations: {}
#Args:
#  - --daemon

# To use exposecontroller you probably want to enable it in helm hooks, here's an example values.yaml:

# annotations:
#   helm.sh/hook: post-install
#   helm.sh/hook-delete-policy: hook-succeeded

# cleanup:
#   annotations:
#     helm.sh/hook: pre-delete
#     helm.sh/hook-delete-policy: hook-succeeded
#   args: [--cleanup]